"""Initial migration.

Revision ID: bbe50555767a
Revises: 
Create Date: 2020-07-19 09:50:21.365987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe50555767a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eye_patient', sa.Column('date_added', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eye_patient', 'date_added')
    # ### end Alembic commands ###
